import { Sora } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import Header from "./components/header/Header";
import Footer from "./components/Footer/Footer";
import MobileHeader from "./components/header/MobileHeader";
import SmoothScrolling from "./utils/SmoothScrolling";
import AosProvider from "./utils/AosProvider"


const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`page page-enter ${sora.className}`}>
        <SmoothScrolling>
          <AosProvider>
            <Header />
            <MobileHeader />
            {children}
            <Footer />
          </AosProvider>
        </SmoothScrolling>

      </body>
    </html>
  );
}
