import { Sora } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import Header from "./components/header/Header";
import Footer from "./components/Footer/Footer";
import MobileHeader from "./components/header/MobileHeader";
import SmoothScrolling from "./utils/SmoothScrolling";


const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`page page-enter ${sora.className}`}>
        <SmoothScrolling>
          <Header />
          <MobileHeader />
          {children}
          <Footer />
        </SmoothScrolling>

      </body>
    </html>
  );
}
